
INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
VALUES ('RoomBookingEntity', 2, '2019-04-09', '2019-04-12', 2, 4, 'ASDASDLKAHKSJDLASH', '0', 'SUR', NULL, 'MANUAL', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
VALUES ('RoomBookingEntity', 4, '2019-04-03', '2019-04-05', 2, 3, 'LLLLSDLKAHKSJDLASH', '0', 'SUR', NULL, 'MANUAL', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
	VALUES ('RoomBookingEntity', 3, '2019-04-02', '2019-04-06', 2, 5, 'ADSASDLKOHKSJDLASH', '0', 'DEX', NULL, 'MANUAL', 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
VALUES ('RoomBookingEntity', 3, '2019-04-09', '2019-04-11', 2, 3, 'ASDASLDKOHKSJDLASH', '0', 'JUN', NULL, 'MANUAL', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
	VALUES ('RoomBookingEntity', 4, '2019-04-06', '2019-04-09', 2, 4, 'ASDASLDKKKKSJDKKSH', '201', 'DEX', NULL, 'CHECKED_IN', 5, 2, NULL, NULL, NULL, NULL, NULL, NULL);




INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
	VALUES ('BookOnBehalfEntity', 3, '2019-12-04', '2019-12-06', 3, 3, 'AAASSSLKAHKSJDLASH', '0', 'SUR', NULL, 'MANUAL', 2, NULL, 'bernicecpz@gmail.com', 'Bernice', 'Choy', NULL, NULL, NULL);

INSERT INTO IS4103.ROOMBOOKINGENTITY (DTYPE, ADULTCOUNT, CHECKINDATETIME, CHECKOUTDATETIME, CHILDCOUNT, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, ROOMTYPECODE, SPECIALREQUESTS, STATUS, CUSTOMER_CUSTOMERID, ROOMTYPE_ROOMTYPEID, GUESTEMAIL, GUESTFIRSTNAME, GUESTLASTNAME, COMPANYNAME, GROUPBOOKINGTYPE, ROOMTYPEQUANTITYJSON) 
	VALUES ('GroupBookingEntity', 50, '2019-12-04', '2019-12-07', 5, 4, 'HHHSSSLKAHKSJDLASH', '0', 'SUR', NULL, 'MANUAL', 4, NULL, NULL, NULL, NULL, 'JTA Corporation', 'CORPORATE', '{"EXE":10,"SUP":5}');

  forcastSessionLocal.createTestRoomBooking(new RoomBookingEntity(2,java.sql.Date.valueOf("2019-03-14"), java.sql.Date.valueOf("2019-03-20"), 5, 2, "AAA","0", "SUR", "NULL", RoomBookingStatusEnum.MANUAL,customerSessionLocal.retrieveForHouseKeeping(2L),room1));
  