--Include hotels, rooms, roomtype, customer, payment method, roombooking

-- INSERT HOTELS
INSERT INTO IS4103.HOTELENTITY (ADDRESS, COUNTRY, DESCRIPTION, EMAIL, HOTELURL, "NAME", POLICIES, SERVICES, TELEPHONENUMBER) 
	VALUES ('Tampines North Road Ave 8', 'Singapore', 'Hotel A', 'hotelA@krhg.com', 'http://localhost:81', 'Hotel A', NULL, NULL, NULL);
INSERT INTO IS4103.HOTELENTITY (ADDRESS, COUNTRY, DESCRIPTION, EMAIL, HOTELURL, "NAME", POLICIES, SERVICES, TELEPHONENUMBER) 
	VALUES ('Tampines North Road Ave 9', 'Singapore', 'Hotel B', 'hotelB@krhg.com', 'http://localhost:81', 'Hotel B', NULL, NULL, NULL);
INSERT INTO IS4103.HOTELENTITY (ADDRESS, COUNTRY, DESCRIPTION, EMAIL, HOTELURL, "NAME", POLICIES, SERVICES, TELEPHONENUMBER) 
	VALUES ('Tampines North Road Ave 10', 'Singapore', 'Hotel C', 'hotelC@krhg.com', 'http://localhost:81', 'Hotel C', NULL, NULL, NULL);
INSERT INTO IS4103.HOTELENTITY (ADDRESS, COUNTRY, DESCRIPTION, EMAIL, HOTELURL, "NAME", POLICIES, SERVICES, TELEPHONENUMBER) 
	VALUES ('Tampines North Road Ave 11', 'Singapore', 'Hotel D', 'hotelD@krhg.com', 'http://localhost:81', 'Hotel D', NULL, NULL, NULL);
INSERT INTO IS4103.HOTELENTITY (ADDRESS, COUNTRY, DESCRIPTION, EMAIL, HOTELURL, "NAME", POLICIES, SERVICES, TELEPHONENUMBER) 
	VALUES ('Tampines North Road Ave 12', 'Singapore', 'Hotel E', 'hotelE@krhg.com', 'http://localhost:81', 'Hotel E', NULL, NULL, NULL);

--INSERT ROOM TYPES	(Commented out cause Singleton creates the room type)
-- INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) VALUES ('Superior', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'SUP', NULL, 1, NULL);
-- INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) VALUES ('Deluxe', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'DEL', NULL, 2, NULL);
-- INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) VALUES ('Junior Suite', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'JUN', NULL, 3, NULL);
-- INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) VALUES ('Executive Suite', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'EXE', NULL, 4, NULL);
-- INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) VALUES ('President Suite', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'PRE', NULL, 5, NULL);

	
-- INSERT ROOMS For 1 HOTELENTITY
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1040, NULL, 1, NULL, NULL, 1);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1041, NULL, 1, NULL, NULL, 2);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1042, NULL, 1, NULL, NULL, 3);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1043, NULL, 1, NULL, NULL, 4);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1044, NULL, 1, NULL, NULL, 5);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1045, NULL, 1, NULL, NULL, 6);

-- SUPERIOR
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88, 132, 50, 'Leisure rate','Leisure rate for Superior room type', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88, 123.20, 40, 'Standard rate','Standard rate for Superior room type', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88, 114.40, 30, 'Group rate','Group rate for Superior room type', NULL, 1);
	

-- DELUXE
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188, 282, 50, 'Leisure rate','Price rate for Deluxe room type', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188, 263.20, 40, 'Standard rate','Price rate for Deluxe room type', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188, 244.40, 30, 'Group rate','Group rate for Deluxe room type', NULL, 2);
	
-- JUNIOR SUITE
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288, 432, 50, 'Leisure rate','Price rate for Junior Suite room type', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288, 403.20, 40, 'Standard rate','Price rate for Junior Suite room type', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288, 374.40, 30, 'Group rate','Group rate for Junior Suite room type', NULL, 3);	
	
-- EXECUTIVE SUITE
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (388, 698.40, 80, 'Leisure rate','Price rate for Executive Suite room type', NULL, 4);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (388, 659.60, 70, 'Standard rate','Price rate for Executive Suite room type', NULL, 4);

-- PRESIDENT SUITE	
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (488, 878.40, 50, 'Premier rate','Price rate for Executive Suite room type', NULL, 5);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (488, 829.60, 40, 'Premier Leisure rate','Price rate for Executive Suite room type', NULL, 5);
	



--INSERT CUSTOMERS	
INSERT INTO IS4103.CUSTOMERENTITY (BIRTHDATE, CUSTIDENTITY, EMAIL, FIRSTJOINED, FIRSTNAME, LASTNAME, MEMBERSHIPSTATUS, PASSWORD, PHONENUM, LOYALTY_LOYALTYPOINTID) 
	VALUES ('1996-03-29','S9631677E','bernicecpz@gmail.com', '2019-02-21', 'Bernice','Choy','MEMBER','E6245C923E518C54ED49499311F120B18FC16C91','91092348',NULL);

-- INSERT STAFF
INSERT INTO IS4103.STAFFENTITY (DTYPE, BONUS, DATEOFBIRTH, DEPARTMENT, GENDER, HOMENUM, IC_NUM, JOBPOSITION, JOBTITLE, JOBTYPE, LEAVEQUOTA, "NAME", NATIONALITY, PASSWORD, PHONENUM, SALARY, STAFFSTATUS, USERNAME, TRAININGROSTER_TRAININGID, WORKROSTER_WORKROSTERID, RATING, REQUESTACCEPTED) 
	VALUES ('StaffEntity', 300.0, '1993-12-12', 'HUMAN_RESOURCE', 'FEMALE', '67813901', 'S9381791B', 'STAFF', ' Human resource staff', 'FULL_TIME', 14, 'Bell Lim', 'Singapore ', '48E3D4EFE5B0FBB3B1ABC398DB5B6B98F8679C55', '97813901', 2000.0, 'ACTIVE', 'bell_lim69', NULL, NULL, NULL, NULL);
		
-- INSERT PAYMENTMETHODENTITY
INSERT INTO IS4103.PAYMENTMETHODENTITY (CARDNAME, CARDNO, EXPIRYDATE, PAYMENTCODE) 


-- INSERT FEEDBACKENTITY
INSERT INTO IS4103.FEEDBACKENTITY (EMAIL, ISCOMPLETED, RATINGS) 
	VALUES ('bernicecpz@gmail.com', 0, NULL);

-- INSERT PAYMENTENTITY
INSERT INTO IS4103.PAYMENTENTITY (PAYMENTCODE, TOTALAMOUNT, PAYMENTMETHOD_PAYMENTMETHODID, TRANSACTION_TRANSACTIONID) 
	VALUES (1, 263, 1, NULL);
	
-- INSERT ROOMBOOKING
INSERT INTO IS4103.ROOMBOOKINGENTITY (CHECKINDATETIME, CHECKOUTDATETIME, NUMOFDAYS, RESERVATIONNUMBER, ROOMNUMBER, SPECIALREQUESTS, STATUS, TOTALAMOUNT, CUSTOMER_CUSTOMERID, ROOMENTITY_ROOMID, FEEDBACK_FEEDBACKID, PAYMENT_PAYMENTID) 
	VALUES ('2019-03-05', '2019-03-08', 4, 'ASDASDASD1', NULL, NULL, NULL, 263, 1, 1, 1, 1);
