-- AffiliateContentEntity
INSERT INTO IS4103.AFFILIATECONTENTENTITY (AFFILIATECONTENTSTATE, AFFILIATECONTENTSTATUS, CATEGORY, PROMOCODE, PROMODESCRIPTION, PROMOTIONENDDATE, PROMOTIONSTARTDATE, TITLE, AFFILIATE_AFFILIATEID, PICTURE_PICID) 
	VALUES ('VISIBLE', 'APPROVED', 'TOURIST_SITE', 'KRHGSTB362', 'We are offering 50% off for your first purchase of tourist passes now. The tourist entitles you to visit Singapore’s top attraction with great savings.', '2021-06-06 00:00:00.0', '2019-01-01 00:00:00.0', 'Get 50% off for Singapore Tourist Pass Now', 1, NULL);

INSERT INTO IS4103.AFFILIATECONTENTENTITY (AFFILIATECONTENTSTATE, AFFILIATECONTENTSTATUS, CATEGORY, PROMOCODE, PROMODESCRIPTION, PROMOTIONENDDATE, PROMOTIONSTARTDATE, TITLE, AFFILIATE_AFFILIATEID, PICTURE_PICID) 
	VALUES ('VISIBLE', 'APPROVED', 'RESTAURANT', 'KRHGSMRT362', 'We are offering up to 20% discount when shopping in any of our participating station merchants now. Enjoy Food, Clothings and much more at our stations.', '2021-06-06 00:00:00.0', '2019-01-01 00:00:00.0', 'Get up to 20% off in our participating stations now', 3, NULL);

INSERT INTO IS4103.AFFILIATECONTENTENTITY (AFFILIATECONTENTSTATE, AFFILIATECONTENTSTATUS, CATEGORY, PROMOCODE, PROMODESCRIPTION, PROMOTIONENDDATE, PROMOTIONSTARTDATE, TITLE, AFFILIATE_AFFILIATEID, PICTURE_PICID) 
	VALUES ('VISIBLE', 'APPROVED', 'TOURIST_SITE', 'KRHHGSMRT363', 'We are offering 10% off for your first purchase of travel passes now. Enjoy great savings with our travel passes. Limited Time Only!', '2019-06-06 00:00:00.0', '2019-01-01 00:00:00.0', 'Get 10% off for your first purchase of travel passes now', 3, NULL);

INSERT INTO IS4103.AFFILIATECONTENTENTITY (AFFILIATECONTENTSTATE, AFFILIATECONTENTSTATUS, CATEGORY, PROMOCODE, PROMODESCRIPTION, PROMOTIONENDDATE, PROMOTIONSTARTDATE, TITLE, AFFILIATE_AFFILIATEID, PICTURE_PICID) 
	VALUES ('VISIBLE', 'APPROVED', 'TOURIST_SITE', 'KRHGVIVO362', 'We are offering up to 10% off mall wide for this shopping season', '2019-06-06 00:00:00.0', '2019-04-01 00:00:00.0', 'Get 10% off Mall Wide here at Vivo City Mall', 5, NULL);

INSERT INTO IS4103.AFFILIATECONTENTENTITY (AFFILIATECONTENTSTATE, AFFILIATECONTENTSTATUS, CATEGORY, PROMOCODE, PROMODESCRIPTION, PROMOTIONENDDATE, PROMOTIONSTARTDATE, TITLE, AFFILIATE_AFFILIATEID, PICTURE_PICID) 
	VALUES ('VISIBLE', 'APPROVED', 'RESTAURANT', 'KRHGMBS362', 'We are offering up to 15% off for great dining experience at our participating merchants.', '2019-06-06 00:00:00.0', '2019-01-01 00:00:00.0', 'Get up to 15% off for great dining at Marina Bays Sands', 4, NULL);
