-- Affiliate
INSERT INTO IS4103.AFFILIATEENTITY (AFFILIATENAME, AFFILIATESTATUS, AFFILIATETYPE, BUSINESSADDRESS, CONTACTNUMBER, EMAIL, ORGANIZATIONENTITYNUMBER, REPRESENTATIVENAME) 
	VALUES ('Singapore Tourism Board', 'PENDING', 'GOVERNMENT', 'Tourism Court, 1 Orchard Spring Lane, 247729', '64565789', 'tanchinkwow@stb.gov', 'T08GB0059L', 'Mr. Tan Chin Kwok');

INSERT INTO IS4103.AFFILIATEENTITY (AFFILIATENAME, AFFILIATESTATUS, AFFILIATETYPE, BUSINESSADDRESS, CONTACTNUMBER, EMAIL, ORGANIZATIONENTITYNUMBER, REPRESENTATIVENAME) 
	VALUES ('Changi Airport Group', 'PENDING', 'GOVERNMENT', '60, AIRPORT BOULEVARD, #46-37, CHANGI AIRPORT TERMINAL 2, SINGAPORE 819643', '86083522', 'ivantan@changiairport.com', '200910817N', 'Mr. Ivan Tan');

INSERT INTO IS4103.AFFILIATEENTITY (AFFILIATENAME, AFFILIATESTATUS, AFFILIATETYPE, BUSINESSADDRESS, CONTACTNUMBER, EMAIL, ORGANIZATIONENTITYNUMBER, REPRESENTATIVENAME) 
	VALUES ('SMRT Corporation Ltd', 'PENDING', 'GOVERNMENT', '251 North Bridge Rd, Singapore 179102', '68201239' ,'leefooksun@smrt.com', '200001855H', 'Mr. Lee Fook Sun');

INSERT INTO IS4103.AFFILIATEENTITY (AFFILIATENAME, AFFILIATESTATUS, AFFILIATETYPE, BUSINESSADDRESS, CONTACTNUMBER, EMAIL, ORGANIZATIONENTITYNUMBER, REPRESENTATIVENAME) 
	VALUES ('Marina Bay Sands Pte Ltd', 'PENDING', 'GOVERNMENT', '80, ROBINSON ROAD, #02-00, SINGAPORE 068898','60128382','leekwokfung@mbs.com', '200507292R', 'Mr. Lee Kwok Fung');

INSERT INTO IS4103.AFFILIATEENTITY (AFFILIATENAME, AFFILIATESTATUS, AFFILIATETYPE, BUSINESSADDRESS, CONTACTNUMBER, EMAIL, ORGANIZATIONENTITYNUMBER, REPRESENTATIVENAME) 
	VALUES ('Vivo Group Pte Ltd', 'PENDING', 'GOVERNMENT', '61, CLUB STREET, SINGAPORE 069436', '69208321', 'chewhuiling@vivogroup.com', '200101914E', 'Ms. Chew Hui Ling');
