-- DeviceEntity
INSERT INTO IS4103.DEVICEENTITY (DEVICECATEGORY, DEVICEMODEL, DEVICESTATE, DEVICESTATUS, LASTMAINTENANCEDATE, MANUFACTURERNAME, SERIALNUMBER, ROOM_ROOMID) 
	VALUES ('TABLET', 'iPad Pro', 'NOT_DEPLOYED', 'WORKING', '2019-02-01 22:37:12.848', 'Apple Inc.', 'X0XXX0X000XX', NULL);

INSERT INTO IS4103.DEVICEENTITY (DEVICECATEGORY, DEVICEMODEL, DEVICESTATE, DEVICESTATUS, LASTMAINTENANCEDATE, MANUFACTURERNAME, SERIALNUMBER, ROOM_ROOMID) 
	VALUES ('SMARTPHONE', 'iPhone 6', 'NOT_DEPLOYED', 'WORKING', '2019-02-01 22:37:12.848', 'Apple Inc.', 'X12XX0X240XX', NULL);

INSERT INTO IS4103.DEVICEENTITY (DEVICECATEGORY, DEVICEMODEL, DEVICESTATE, DEVICESTATUS, LASTMAINTENANCEDATE, MANUFACTURERNAME, SERIALNUMBER, ROOM_ROOMID) 
	VALUES ('TABLET', 'iPad Pro 2', 'NOT_DEPLOYED', 'WORKING', '2019-02-01 22:37:12.848', 'Apple Inc.', 'X12XX0X430XX', NULL);

INSERT INTO IS4103.DEVICEENTITY (DEVICECATEGORY, DEVICEMODEL, DEVICESTATE, DEVICESTATUS, LASTMAINTENANCEDATE, MANUFACTURERNAME, SERIALNUMBER, ROOM_ROOMID) 
	VALUES ('TABLET', 'iPad 2', 'NOT_DEPLOYED', 'WORKING', '2019-02-20 22:37:12.848', 'Apple Inc.', 'X057X0X032XX', NULL);

INSERT INTO IS4103.DEVICEENTITY (DEVICECATEGORY, DEVICEMODEL, DEVICESTATE, DEVICESTATUS, LASTMAINTENANCEDATE, MANUFACTURERNAME, SERIALNUMBER, ROOM_ROOMID) 
	VALUES ('SMARTPHONE', 'iPhone 6', 'NOT_DEPLOYED', 'WORKING', '2019-02-20 22:37:12.848', 'Apple Inc.', 'X012X0X320XX', NULL);			
