INSERT INTO IS4103.LISTMENUITEMENTITY (QUANTITY, SUBTOTAL, MENUITEM_MENUITEMID) 
	VALUES (1, 1.5, 1);

INSERT INTO IS4103.LISTMENUITEMENTITY (QUANTITY, SUBTOTAL, MENUITEM_MENUITEMID) 
	VALUES (1, 1.5, 2);

INSERT INTO IS4103.LISTMENUITEMENTITY (QUANTITY, SUBTOTAL, MENUITEM_MENUITEMID) 
	VALUES (1, 1.5, 3);

INSERT INTO IS4103.LISTMENUITEMENTITY (QUANTITY, SUBTOTAL, MENUITEM_MENUITEMID) 
	VALUES (1, 1.5, 4);

INSERT INTO IS4103.LISTMENUITEMENTITY (QUANTITY, SUBTOTAL, MENUITEM_MENUITEMID) 
	VALUES (1, 1.5, 5);				
