INSERT INTO IS4103.MENUITEMENTITY (CATEGORY, DESCRIPTION, MENUITEMNAME, UNITPRICE, PICTURE_PICID) 
	VALUES (6, 'Lemon Barley Drink that is locally homebrew and made fresh.', 'Lemon Barley Drink', 1.5, NULL);

INSERT INTO IS4103.MENUITEMENTITY (CATEGORY, DESCRIPTION, MENUITEMNAME, UNITPRICE, PICTURE_PICID) 
	VALUES (6, 'Delicious Hot Chocolate Drink. Perfect for a cold day', 'Hot Chocolate', 2.5, NULL);

INSERT INTO IS4103.MENUITEMENTITY (CATEGORY, DESCRIPTION, MENUITEMNAME, UNITPRICE, PICTURE_PICID) 
	VALUES (6, 'Pure Nutritious Coconut juice for a tropical experience.', 'Coconut Juice', 3.0, NULL);

INSERT INTO IS4103.MENUITEMENTITY (CATEGORY, DESCRIPTION, MENUITEMNAME, UNITPRICE, PICTURE_PICID) 
	VALUES (6, 'Fragrant Mocha for that perfect morning.', 'Mocha', 1.5, NULL);

INSERT INTO IS4103.MENUITEMENTITY (CATEGORY, DESCRIPTION, MENUITEMNAME, UNITPRICE, PICTURE_PICID) 
	VALUES (6, 'Local Special Teh Tarik.', 'Teh Tarik', 2.0, NULL);