-- Merchandise
INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
	VALUES (300, 'Our Exclusive Floral Bracelet for our exclusive members of Kent Ridge Hotel Group. Comes with the floral design of our diverse local flowers.', 1, 400, 'NOT_ON_SALE', 'Exclusive Floral Bracelet', 50, 100, NULL);

INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
	VALUES (500, 'Our Exclusive Floral Necklace for our exclusive members of Kent Ridge Hotel Group. Comes with the floral design of our diverse local flowers.', 1, 700, 'NOT_ON_SALE', 'Exclusive Floral Necklace', 50, 100, NULL);

INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
	VALUES (200, 'Our Exclusive Floral Earrings for our exclusive members of Kent Ridge Hotel Group. Comes with the floral design of our diverse local flowers.', 1, 400, 'NOT_ON_SALE', 'Exclusive Floral Earrings', 50, 100, NULL);

INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
	VALUES (100, 'Our Exclusive Local Postcards for our exclusive members of Kent Ridge Hotel Group. ', 1, 100, 'NOT_ON_SALE', 'Exclusive Local PostCards', 50, 100, NULL);

INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
	VALUES (50, 'Our Exclusive Coffee Mug for our exclusive members of Kent Ridge Hotel Group.', 1, 100, 'NOT_ON_SALE', 'Exclusive Floral Bracelet', 50, 100, NULL);


-- -- Merchandise
-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (300, 'Our Exclusive Floral Bracelet for our exclusive members of Kent Ridge Hotel Group. Comes with the floral design of our diverse local flowers.', 1, 400, 'NOT_ON_SALE', 'Exclusive Floral Bracelet', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (500, 'Our Exclusive Floral Necklace for our exclusive members of Kent Ridge Hotel Group. Comes with the floral design of our diverse local flowers.', 1, 700, 'NOT_ON_SALE', 'Exclusive Floral Necklace', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (200, 'Our Exclusive Floral Earrings for our exclusive members of Kent Ridge Hotel Group. Comes with the floral design of our diverse local flowers.', 1, 400, 'NOT_ON_SALE', 'Exclusive Floral Earrings', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (100, 'Our Exclusive Local Postcards for our exclusive members of Kent Ridge Hotel Group. ', 1, 100, 'NOT_ON_SALE', 'Exclusive Local PostCards', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (50, 'Our Exclusive Coffee Mug for our exclusive members of Kent Ridge Hotel Group.', 1, 100, 'NOT_ON_SALE', 'Exclusive Floral Bracelet', 50, 100, NULL);




-- 
-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (150, 'Our Exclusive Mosaic Cat Figurine for our exclusive members of Kent Ridge Hotel Group.', 1, 300, 'NOT_ON_SALE', 'Exclusive Mosiac Cat', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (250, 'Our Exclusive Russian Dolls for our exclusive members of Kent Ridge Hotel Group. Comes in a set of 7.', 1, 400, 'NOT_ON_SALE', 'Exclusive Russian Dolls', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (199, 'Our Exclusive Nazar Amulet for our exclusive members of Kent Ridge Hotel Group.', 1, 399, 'NOT_ON_SALE', 'Nazar Amulet', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (300, 'Our Exclusive Conical SeaShell for our exclusive members of Kent Ridge Hotel Group.', 1, 400, 'NOT_ON_SALE', 'Conical SeaShell', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (100, 'Our Exclusive Lavender Sachet for our exclusive members of Kent Ridge Hotel Group.', 1, 199, 'NOT_ON_SALE', 'Lavender Sachet', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (200, 'Our Exclusive Baby Clay Figurine for our exclusive members of Kent Ridge Hotel Group.', 1, 400, 'NOT_ON_SALE', 'Exclusive Baby Clay Figurine', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (899, 'Our Exclusive Sapphire Ring for our exclusive members of Kent Ridge Hotel Group.', 1, 1599, 'NOT_ON_SALE', 'Exclusive Sapphire Ring', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (699, 'Our Exclusive Emerald Necklace for our exclusive members of Kent Ridge Hotel Group.', 1, 1399, 'NOT_ON_SALE', 'Exclusive Emerald Necklace', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (175, 'Our Exclusive Romans Helmet Figurines for our exclusive members of Kent Ridge Hotel Group.', 1, 400, 'NOT_ON_SALE', 'Romans Helmet Figurines', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (275, 'Our Exclusive Mosaic Gecko for our exclusive members of Kent Ridge Hotel Group.', 1, 350, 'NOT_ON_SALE', 'Exclusive Mosaic Gecko', 50, 100, NULL);

-- INSERT INTO IS4103.MERCHANDISEENTITY (COSTPOINTS, DESCRIPTION, ISTRIGGERON, MAXCOSTPRICELIMIT, MERCHANDISESTATUS, "NAME", POTRIGGERLEVEL, QUANTITYONHAND, PICTURE_PICID) 
-- 	VALUES (100, 'Our Laughing Buddha Figurines for our exclusive members of Kent Ridge Hotel Group.', 1, 199, 'NOT_ON_SALE', 'Laughing Buddha Figurines', 50, 100, NULL);
