INSERT INTO IS4103.MERCHANDISEORDERENTITY (QUANTITYREDEEMED, STATUS, ROOM_ROOMID) 
	VALUES (1, 2, NULL);
	
INSERT INTO IS4103.MERCHANDISEORDERENTITY (QUANTITYREDEEMED, STATUS, ROOM_ROOMID) 
	VALUES (1, 2, NULL);

INSERT INTO IS4103.MERCHANDISEORDERENTITY (QUANTITYREDEEMED, STATUS, ROOM_ROOMID) 
	VALUES (1, 2, NULL);

INSERT INTO IS4103.MERCHANDISEORDERENTITY (QUANTITYREDEEMED, STATUS, ROOM_ROOMID) 
	VALUES (1, 2, NULL);

INSERT INTO IS4103.MERCHANDISEORDERENTITY (QUANTITYREDEEMED, STATUS, ROOM_ROOMID) 
	VALUES (1, 2, NULL);			