INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-03', 'Atlas Business Consulting Pte Ltd', 'Singapore', 'Banquet leads', 'Joe Tan', 'Convention Booking', 'Banquet size 200', '90547822', 'Group and Banquet', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-06', 'Kenston Construction Pte Ltd', 'Singapore', 'Room leads', 'Victoria Lim', 'Room Booking', 'Two Rooms', '65533275', 'Room Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-10', 'Crossroad Consulting Pte Ltd', 'Malaysia', 'Room leads', 'Layla Sim', 'Room Booking', 'Two Rooms', '64431275', 'Room Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-13', 'PH Consulting Pte Ltd', 'Thailand', 'Banquet only', 'Zoey Tim', 'Convention Booking', 'Banquet size 50', '96531275', 'Banquet Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-15', 'FSC Consultancy Pte Ltd', 'Malaysia', 'Banquet only', 'James Tim', 'Convention Booking', 'Banquet size 80', '96189313', 'Banquet Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-18', 'PI ETA Consulting Pte Ltd', 'Malaysia', 'Banquet only', 'Joshua Tan', 'Convention Booking', 'Banquet size 60', '98185478', 'Banquet Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-22', 'Joshua Consultanting Pte Ltd', 'Malaysia', 'Banquet only', 'Henry Koh', 'Convention Booking', 'Banquet size 90', '84373755', 'Banquet Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-25', 'Alenu IT Business Solutions', 'Vietnam', 'Banquet only', 'William Toh', 'Convention Booking', 'Banquet size 30', '85463877', 'Banquet Only', NULL);
INSERT INTO IS4103.CALLREPORTENTITY (CALLDATE, CALLFROM, CITY, FOLLOWUP, PERSONCONTACTED, REGARDING, REMARKS, TELEPHONENUM, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-02-28', 'Avensys Consulting Pte Ltd1', 'Singapore', '', 'ww', 'g', 'ggg', '87', 'Room and Banquets', NULL);
