INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88.0, 114.4, 30, 'Group', '', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88.0, 123.2, 40, 'Standard', '', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88.0, 132.0, 50, 'Leisure', '', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88.0, 140.8, 60, 'Corporate', '', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (88.0, 167.2, 90, 'Rack', '', NULL, 1);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188.0, 244.4, 30, 'Group', '', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188.0, 263.2, 40, 'Standard', '', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188.0, 282.0, 50, 'Leisure', '', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188.0, 300.8, 60, 'Corporate', '', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (188.0, 357.2, 90, 'Rack', '', NULL, 2);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288.0, 374.4, 30, 'Group', '', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288.0, 403.2, 40, 'Standard', '', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288.0, 432.0, 50, 'Leisure', '', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288.0, 460.8, 60, 'Corporate', '', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (288.0, 547.2, 90, 'Rack', '', NULL, 3);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (388.0, 659.6, 70, 'Premier', '', NULL, 4);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (388.0, 698.4, 80, 'Premier Leisure', '', NULL, 4);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (388.0, 737.2, 90, 'Rack', '', NULL, 4);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (489.0, 829.6, 71, 'Premier', '', NULL, 5);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (488.0, 878.4, 80, 'Premier Leisure', '', NULL, 5);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (488.0, 927.2, 90, 'Rack', '', NULL, 5);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (588.0, 823.2, 40, 'Standard', '', 3, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (588.0, 882.0, 50, 'Leisure', '', 3, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (588.0, 940.8, 60, 'Corporate', '', 3, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (588.0, 1117.2, 90, 'Rack', '', 3, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (688.0, 963.2, 40, 'Standard', '', 4, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (688.0, 1032.0, 50, 'Leisure', '', 4, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (688.0, 1100.8, 60, 'Corporate', '', 4, NULL);
INSERT INTO IS4103.PRICERATEENTITY (BASEPRICE, MARKUPPRICE, PERCENTAGEMARKUP, RATETITLE, REMARKS, FACILITY_FACILITYID, ROOMTYPE_ROOMTYPEID) 
	VALUES (688.0, 1307.2, 90, 'Rack', '', 4, NULL);
