INSERT INTO IS4103.SALESCALLGUIDELINEENTITY (CREATEDATE, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-03-22', 'Guidelines on making personal sales calls', NULL);
INSERT INTO IS4103.SALESCALLGUIDELINEENTITY (CREATEDATE, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-03-22', 'Sales Call Checklist', NULL);
INSERT INTO IS4103.SALESCALLGUIDELINEENTITY (CREATEDATE, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-03-23', 'During Call', NULL);
INSERT INTO IS4103.SALESCALLGUIDELINEENTITY (CREATEDATE, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-03-23', 'Phrases and Expressions used while handling calls', NULL);
INSERT INTO IS4103.SALESCALLGUIDELINEENTITY (CREATEDATE, TITLE, SALESSTAFF_STAFFID) 
	VALUES ('2019-03-23', 'Sales Call Dos:', NULL);
