INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1040, NULL, 1, NULL, NULL, 1);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1041, NULL, 1, NULL, NULL, 1);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1042, NULL, 1, NULL, NULL, 1);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1043, NULL, 1, NULL, NULL, 1);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1044, NULL, 1, NULL, NULL, 1);
INSERT INTO IS4103.ROOMENTITY (ROOMUNITNUMBER, STATUS, HOTEL_HOTELID, HOUSEKEEPINGREQUEST_REQUESTID, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOMTYPE_ROOMTYPEID) 
	VALUES (1045, NULL, 1, NULL, NULL, 1);
