INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) 
	VALUES ('Superior', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'SUP', NULL, 1, NULL);
INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) 
	VALUES ('Deluxe', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'DEL', NULL, 2, NULL);
INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) 
	VALUES ('Junior Suite', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'JUN', NULL, 3, NULL);
INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) 
	VALUES ('Executive Suite', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'EXE', NULL, 4, NULL);
INSERT INTO IS4103.ROOMTYPEENTITY (BEDTYPE, CANCELLATIONPOLICY, DESCRIPTION, "NAME", NUMMAXGUEST, ROOMPOLICY, ROOMSIZE, ROOMTYPEORDER, ROOMTYPESTATUS, ROOMTYPECODE, TOTALROOMS, HOUSEKEEPINGSOP_HOUSEKEEPINGSOPID, ROOM_ROOMID) 
	VALUES ('President Suite', NULL, NULL, NULL, NULL, NULL, 0.0, 0, NULL, 'PRE', NULL, 5, NULL);
